# Generated by Django 5.2.7 on 2025-10-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('bloodgroup', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('qualification', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('income', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
