# Generated by Django 5.2.7 on 2025-10-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_patient_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_appointment',
            name='reason',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='patient_appointment',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
