# Generated by Django 5.2.7 on 2025-10-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_alter_patient_appointment_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicalhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('named', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('dateofbirth', models.DateField()),
                ('genders', models.CharField(max_length=200)),
                ('contactnumber', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('allergy', models.TextField(max_length=10000)),
                ('medication', models.TextField(max_length=10000)),
                ('chronic', models.TextField(max_length=10000)),
                ('surgery', models.TextField(max_length=10000)),
                ('history', models.TextField(max_length=10000)),
                ('comment', models.TextField(max_length=10000)),
            ],
        ),
    ]
