# Generated by Django 5.2.7 on 2025-10-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_medicalhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=100)),
                ('times', models.TimeField()),
                ('plana', models.CharField(max_length=100)),
                ('planb', models.CharField(max_length=100)),
                ('planc', models.CharField(max_length=100)),
                ('pland', models.CharField(max_length=100)),
                ('plane', models.CharField(max_length=100)),
            ],
        ),
    ]
