# Generated by Django 5.2.7 on 2025-10-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0005_doctorschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='times',
            field=models.CharField(max_length=100),
        ),
    ]
