# Generated by Django 5.2.7 on 2025-10-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0006_alter_doctorschedule_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='eprescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=100)),
                ('ages', models.IntegerField()),
                ('medications', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('dated', models.DateField()),
            ],
        ),
    ]
