# Generated by Django 5.2.7 on 2025-10-27 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0007_eprescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eprescription',
            name='dated',
        ),
    ]
