# Generated by Django 5.2.7 on 2025-10-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0008_remove_eprescription_dated'),
    ]

    operations = [
        migrations.AddField(
            model_name='eprescription',
            name='dated',
            field=models.CharField(default='', max_length=200),
        ),
    ]
