# Generated by Django 5.2.7 on 2025-10-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0009_eprescription_dated'),
    ]

    operations = [
        migrations.CreateModel(
            name='treatmentplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naming', models.CharField(max_length=100)),
                ('diagnosis', models.CharField(max_length=100)),
                ('problem', models.CharField(max_length=200)),
                ('goals', models.CharField(max_length=100)),
                ('objectives', models.CharField(max_length=200)),
                ('strategy', models.CharField(max_length=100)),
                ('modality', models.CharField(max_length=100)),
                ('frequencies', models.CharField(max_length=200)),
                ('estimate', models.CharField(max_length=200)),
            ],
        ),
    ]
