# Generated by Django 5.2.7 on 2025-10-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0010_treatmentplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategies', models.TextField()),
                ('objective', models.TextField()),
                ('actionl', models.TextField()),
                ('actionh', models.TextField()),
                ('actionr', models.TextField()),
                ('planl', models.TextField()),
                ('planr', models.TextField()),
                ('planh', models.TextField()),
            ],
        ),
    ]
