# Generated by Django 5.2.7 on 2025-10-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0011_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billnumber', models.IntegerField()),
                ('dateds', models.DateField()),
                ('patientid', models.IntegerField()),
                ('patientname', models.CharField(max_length=100)),
                ('patientage', models.IntegerField()),
                ('patientgender', models.CharField(max_length=100)),
                ('admissiondate', models.DateField()),
                ('dischargedate', models.DateField()),
                ('roomcharge', models.IntegerField()),
                ('doctorfee', models.IntegerField()),
                ('pathology', models.IntegerField()),
                ('misc', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
